# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: otp.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'otp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\totp.proto\x12\x03otp\"#\n\x12GenerateOTPRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"7\n\x13GenerateOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\".\n\x10VerifyOTPRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"5\n\x11VerifyOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8e\x01\n\nOTPService\x12\x42\n\x0bGenerateOTP\x12\x17.otp.GenerateOTPRequest\x1a\x18.otp.GenerateOTPResponse\"\x00\x12<\n\tVerifyOTP\x12\x15.otp.VerifyOTPRequest\x1a\x16.otp.VerifyOTPResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEOTPREQUEST']._serialized_start=18
  _globals['_GENERATEOTPREQUEST']._serialized_end=53
  _globals['_GENERATEOTPRESPONSE']._serialized_start=55
  _globals['_GENERATEOTPRESPONSE']._serialized_end=110
  _globals['_VERIFYOTPREQUEST']._serialized_start=112
  _globals['_VERIFYOTPREQUEST']._serialized_end=158
  _globals['_VERIFYOTPRESPONSE']._serialized_start=160
  _globals['_VERIFYOTPRESPONSE']._serialized_end=213
  _globals['_OTPSERVICE']._serialized_start=216
  _globals['_OTPSERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
