# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'reports.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreports.proto\x12\x07reports\">\n\rReportRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\t\x12\r\n\x05month\x18\x03 \x01(\t\"E\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\treport_id\x18\x03 \x01(\t2T\n\rReportService\x12\x43\n\x0eGenerateReport\x12\x16.reports.ReportRequest\x1a\x17.reports.ReportResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reports_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTREQUEST']._serialized_start=26
  _globals['_REPORTREQUEST']._serialized_end=88
  _globals['_REPORTRESPONSE']._serialized_start=90
  _globals['_REPORTRESPONSE']._serialized_end=159
  _globals['_REPORTSERVICE']._serialized_start=161
  _globals['_REPORTSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
